application:
  name: "bitbot"
  project: "BitByte"
  organization: "QoveryCommunity"
databases:
- type: "REDIS"
  name: "the-data"
  version: "6"
routers:
- name: "main-bitbot"
  routes:
  - application_name: "bitbot"
    paths:
    - "/"
